### ISSUE TITLE
how to install the env

### ISSUE THREAD

**Issue by seiya-annie** [lonng/tidiff#4]
hi,

I want to try this tool. but how can I set up the env?
install a MySQL and a Tidb?
then build the project and config?

**Comment by neilydhan** [comment]
Hi @seiya-annie ,
You can follow the documentation here to get it started, https://docs.pingcap.com/tidb/stable/quick-start-with-tidb/

**Comment by dveeden** [comment]
Yes: Install MySQL and TiDB (via TiUP or any other method) and then run the tool and give it the right host, username and password for both.

Building the tool can be done with `go build`
